[package]
name = "krab-runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
sharded-slab = "0.1.7"
crossbeam-channel = "0.5.12"
rayon = "1.10.0"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"